### PR TITLE
Fix iOS 9 bug

### PR DESCRIPTION
**Pull request by Bandd-k**
I have fixed bug with square instead circle.

### CODE REVIEW

**Comment by mpclarkson** [comment]
Pls merge!

**Comment by shergin** [comment]
PLEASE MERGE!!11

**Comment by jingx23** [comment]
+1 merge plz

**Comment by EmilYo** [comment]
It looks like this repo is abandoned. Creator didn't add it to CocoaPods from March.

**Comment by mpclarkson** [comment]
I've forked the repo, fixed the big  and now use this in my pod file https://github.com/mpclarkson/UIBarButtonItem-Badge

**Comment by EmilYo** [comment]
@mpclarkson what should I use your branch, when I can use @Bandd-k ? BTW you fixed nothing. @Bandd-k fixed this bug. you only forked his repo.

**Comment by mpclarkson** [comment]
Ah sorry, yeah I must have forked his repo. It was a while ago :(

Add this to your pod file `pod 'UIBarButtonItem-Badge', :git => 'https://github.com/mpclarkson/UIBarButtonItem-Badge' `

**Pull request merged**
